name: Update EDL List

on:
  schedule:
    # # Runs at 05:00 UTC every day
    # - cron: '0 5 * * *'
    # Runs at 03:00 UTC every day
    - cron: '* 3 * * *'
  workflow_dispatch:

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script to update list
        run: |
          python update_list.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add edl_list.txt
          git commit -m "chore: Automated EDL list update" || echo "No changes to commit"

          git push
